### ISSUE TITLE
Bug: expanded top bar hides first search result

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs-theme#43]
In #41, we expanded the top bar to be two-rows-tall.

It is now hiding the first search result: 

![image](https://github.com/camunda/camunda-docs-theme/assets/1627089/340206bc-b9a0-4a0e-a38c-530d918d3824)

During review of #41 we noticed this effect for content on the page. We didn't notice it for the search results. The fix for this issue is likely similar.

See https://camunda.slack.com/archives/C026U8GBNSW/p1696854277613959 for initial report.

**Comment by akeller** [comment]
Might be good to check in with https://camunda.slack.com/archives/C03NEE32Y2F and see if they are even interested in keeping this around.

**Comment by pepopowitz** [comment]
Per https://camunda.slack.com/archives/C03NEE32Y2F/p1697727164945549?thread_ts=1689199837.690119&cid=C03NEE32Y2F, they would like to keep this around. I'll work on fixing this bug.

**Comment by pepopowitz** [comment]
Resolved in #44 and #47! (And all the PRs linked to from those PRs.)
